# Generated by Django 2.2.4 on 2019-08-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20190818_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='aplicacao_metodo',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='sobrenome',
            new_name='dados_justifica',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='remuneracao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tempo_de_servico',
        ),
        migrations.AddField(
            model_name='produto',
            name='metodo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='metodo_analise',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='natureza_resultado',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='qtde_dado',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='questao_de_pesquisa',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_dado',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
