# Generated by Django 2.2.4 on 2019-08-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_auto_20190819_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='questao_de_pesquisa',
            field=models.TextField(max_length=255),
        ),
    ]
