# Generated by Django 2.2.4 on 2019-08-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_auto_20190820_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='aplicacao_metodo',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dados_justifica',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='metodo',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='metodo_analise',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='natureza_resultado',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtde_dado',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_dado',
            field=models.TextField(max_length=255),
        ),
    ]
