# Generated by Django 2.2.4 on 2019-08-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_auto_20190820_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FilePathField(path='/arquivos')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='aplicacao_metodo',
            field=models.TextField(help_text='(Decisões relacionadas ao modo como o método foi aplicado)', max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='metodo',
            field=models.TextField(help_text='(Nome dos métodos aplicados)', max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='questao_de_pesquisa',
            field=models.TextField(help_text='(Que perguntas se quer responder com o método?)', max_length=255),
        ),
    ]
