# Generated by Django 2.2.4 on 2019-08-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_auto_20190820_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
